// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlTSoeSAvR-XZ51DXOfdLS4oeMsFkqVzQ',
    appId: '1:700252094941:web:5cec162ae6629d84c3b634',
    messagingSenderId: '700252094941',
    projectId: 'nnnk-1a5d0',
    authDomain: 'nnnk-1a5d0.firebaseapp.com',
    storageBucket: 'nnnk-1a5d0.appspot.com',
    measurementId: 'G-XL59L54XRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMj-kW8CvfyaO_bAokda6wd8-dnjqK3SQ',
    appId: '1:700252094941:android:d2a80437b73da6b3c3b634',
    messagingSenderId: '700252094941',
    projectId: 'nnnk-1a5d0',
    storageBucket: 'nnnk-1a5d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsivOj3f-dVqNnXrDVgkVVsj0eJdLw_ME',
    appId: '1:700252094941:ios:52960fde8ea1473cc3b634',
    messagingSenderId: '700252094941',
    projectId: 'nnnk-1a5d0',
    storageBucket: 'nnnk-1a5d0.appspot.com',
    iosClientId: '700252094941-niurl21j905b90rpl99jsenp3529reak.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsivOj3f-dVqNnXrDVgkVVsj0eJdLw_ME',
    appId: '1:700252094941:ios:52960fde8ea1473cc3b634',
    messagingSenderId: '700252094941',
    projectId: 'nnnk-1a5d0',
    storageBucket: 'nnnk-1a5d0.appspot.com',
    iosClientId: '700252094941-niurl21j905b90rpl99jsenp3529reak.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication18',
  );
}
